- name: install python 
  ansible.builtin.import_role:
    name: common
    task_from: python-setup

- name: app setup
  ansible.builtin.import_role:
    name: common
    task_from: app-setup

- name: install dependencies
  ansible.builtin.command: pip3.6 install -r requirements.txt
  args:
    chdir: /app

- name: systemd and service 
  ansible.builtin.import_role:
    name: common
    task_from: systemd-service
    