
# need to refer nodjs tasks in common folder
#catalogue is one role
#common is another role
#imort a task nodejs.yaml in catalogue

- name: setup NPS source
  ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"

- name: install NodeJS
  ansible.builtin.import_role:
    name: common 
    tasks_from: 

- name: setup application
  ansible.builtin.import_role"
  name: common
  tasks_from: app-setup

- name: install npm dependencies
  ansible.builtin.command: npm install
    args:
      chdir: /app
