
# need to refer nodjs tasks in common folder
#catalogue is one role
#common is another role
#imort a task nodejs.yaml in catalogue

- name: install NodeJS
  ansible.builtin.import_role:
    name: common 
    tasks_from: nodejs-setup 

- name: setup application
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: install npm dependencies
  ansible.builtin.command: npm install
  args:
      chdir: /app

- name: load schema 
  ansible.builtin.import_role:
    name: common
    task_from: load-mongo-schema

- name: systemd service
  ansible.builtin.import_role:
    name: common
    task_from: systemd-service