- name: setup NPS source
  ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"

- name: install NodeJS
  ansible.builtin.yum:
    name: nodejs 
    state: installed
    
- name: install npm dependencies
  ansible.builtin.command: npm install
    args:
      chdir: /app
