- name: copy mongo repo to yum.repos.d
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: installing mongodb client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: load mongo data
  ansible.builtin.command: mongo --host mongodb.awsdevops.site < /app/schema/{{component}}.js